### ISSUE TITLE
Bug - Incorrect colors, for example primary, in MS Edge

### ISSUE THREAD

**Issue by mmexvr** [scania/scania-theme#41]
**Describe the bug**
In Microsoft Edge the colors are incorrect

**To Reproduce**
1. Go to any page with Corporate-ui 4
2. Look at something that uses the color variables

**Expected behavior**
Show the correct colors for primary and so on

**Screenshots**
![image](https://user-images.githubusercontent.com/35451568/65136434-dd10c200-da07-11e9-8a6b-3d26d5e63549.png)

**Version of Corporate-ui**
- 4.0.0-alpha

**Desktop (please complete the following information):**
 - OS: Windowns
 - Browser Edge

**Comment by helloimela** [comment]
Initial investigation result:
We don't render css-vars value containing correct Scania colors in IE style data, it is fine and not a problem for IE because IE cannot understand css vars. But Edge can understand css vars, so it takes value from bootstrap :root variables. Solution: add css vars to the :root selector for IE theme.
